server:
  build: server/
  links:
   - mongodb:mongodb
  ports:
   - "3000:3000"
  environment:
    - DB_IP=mongodb

client:
  build: client/
  ports:
   - "80:80"
  environment:
    - VIRTUAL_HOST=bitshares-zone.com
    - VIRTUAL_PORT=80

mongodb:
  image: mongo
